// This file is auto-generated by scripts/generate-photo-list.js
// Do not edit this file manually

export interface PhotoList {
  photos: string[];
  generatedAt: string;
}

export const PHOTO_LIST: PhotoList = {
  photos: [
  "DSC02504.JPG",
  "DSC02669.jpg",
  "DSC03045.JPG",
  "DSC03347.JPG",
  "DSC03503.jpg",
  "DSC03625.JPG",
  "DSC03658.jpg",
  "DSC03705.JPG",
  "DSC03850.jpg",
  "DSC03898.JPG",
  "DSC04000.JPG",
  "DSC04062.JPG",
  "DSC04147.jpg",
  "DSC04180.jpg",
  "DSC04194.jpg",
  "DSC04221.jpg",
  "DSC04285.jpg",
  "DSC04343.JPG",
  "DSC04577.jpg",
  "DSC04607.JPG",
  "DSC04713.jpg"
],
  generatedAt: '2025-08-26T18:43:44.279Z',
};

