// This file is auto-generated by scripts/generate-photo-list.js
// Do not edit this file manually

export interface PhotoList {
  photos: string[];
  generatedAt: string;
}

export const PHOTO_LIST: PhotoList = {
  photos: [
    'DSC02504.JPG',
    'DSC02669.jpg',
    'DSC03045.JPG',
    'DSC03503.jpg',
    'DSC03625.JPG',
    'DSC03658.jpg',
    'DSC03705.JPG',
    'DSC03850.jpg',
    'DSC04000.JPG',
    'DSC04062.JPG',
    'DSC04180.jpg',
    'DSC04194.jpg',
    'DSC04221.jpg',
    'DSC04285.jpg',
    'DSC04577.jpg',
    'DSC04607.JPG',
    'DSC04713.jpg',
  ],
  generatedAt: '2025-08-26T16:55:35.162Z',
};
