name: CI
on:
  push:
    branches:
      - develop
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: run build
        run: pnpm build
      - name: run Lighthouse CI
        run: |
          pnpm add -g @lhci/cli@0.13.x
          lhci autorun --config=./lighthouserc.js
        env:
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
